package com.note.fiction.entity;

import java.util.Date;

public class FictionRankEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String logicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.fiction_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String fictionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.fiction_name
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String fictionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.fiction_score
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer fictionScore;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.fiction_views
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer fictionViews;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.create_user_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String createUserCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fiction_rank.modify_user_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String modifyUserCode;

    public Integer getCid() {
        return cid;
    }

    public void setCid(Integer cid) {
        this.cid = cid;
    }

    public String getLogicCode() {
        return logicCode;
    }

    public void setLogicCode(String logicCode) {
        this.logicCode = logicCode;
    }

    public String getFictionCode() {
        return fictionCode;
    }

    public void setFictionCode(String fictionCode) {
        this.fictionCode = fictionCode;
    }

    public String getFictionName() {
        return fictionName;
    }

    public void setFictionName(String fictionName) {
        this.fictionName = fictionName;
    }

    public Integer getFictionScore() {
        return fictionScore;
    }

    public void setFictionScore(Integer fictionScore) {
        this.fictionScore = fictionScore;
    }

    public Integer getFictionViews() {
        return fictionViews;
    }

    public void setFictionViews(Integer fictionViews) {
        this.fictionViews = fictionViews;
    }

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    public String getCreateUserCode() {
        return createUserCode;
    }

    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode;
    }

    public String getModifyUserCode() {
        return modifyUserCode;
    }

    public void setModifyUserCode(String modifyUserCode) {
        this.modifyUserCode = modifyUserCode;
    }
}