package com.note.fiction.entity;

import java.util.Date;

public class SystemBaseConstEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String logicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.module
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String module;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.key
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.value
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.desc
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Integer isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.create_user_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String createUserCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column system_base_const.modify_user_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    private String modifyUserCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.cid
     *
     * @return the value of system_base_const.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.cid
     *
     * @param cid the value for system_base_const.cid
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.logic_code
     *
     * @return the value of system_base_const.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getLogicCode() {
        return logicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.logic_code
     *
     * @param logicCode the value for system_base_const.logic_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setLogicCode(String logicCode) {
        this.logicCode = logicCode == null ? null : logicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.module
     *
     * @return the value of system_base_const.module
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.module
     *
     * @param module the value for system_base_const.module
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.key
     *
     * @return the value of system_base_const.key
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.key
     *
     * @param key the value for system_base_const.key
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.value
     *
     * @return the value of system_base_const.value
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.value
     *
     * @param value the value for system_base_const.value
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.desc
     *
     * @return the value of system_base_const.desc
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.desc
     *
     * @param desc the value for system_base_const.desc
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.is_delete
     *
     * @return the value of system_base_const.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.is_delete
     *
     * @param isDelete the value for system_base_const.is_delete
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.create_time
     *
     * @return the value of system_base_const.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.create_time
     *
     * @param createTime the value for system_base_const.create_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.modify_time
     *
     * @return the value of system_base_const.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.modify_time
     *
     * @param modifyTime the value for system_base_const.modify_time
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.create_user_code
     *
     * @return the value of system_base_const.create_user_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getcreateUserCode() {
        return createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.create_user_code
     *
     * @param createUserCode the value for system_base_const.create_user_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setcreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode == null ? null : createUserCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_base_const.modify_user_code
     *
     * @return the value of system_base_const.modify_user_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public String getmodifyUserCode() {
        return modifyUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_base_const.modify_user_code
     *
     * @param modifyUserCode the value for system_base_const.modify_user_code
     *
     * @mbg.generated Sat Feb 25 22:52:36 CST 2017
     */
    public void setmodifyUserCode(String modifyUserCode) {
        this.modifyUserCode = modifyUserCode == null ? null : modifyUserCode.trim();
    }
}